# miqin configuration

# UI language: "ko" (Korean) or "en" (English)
ui_language = "ko"

# Number of sentences to practice per session
sentences_per_session = 30

# List of paths to apkg files
apkg_files = [
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 1 Sentences.apkg",
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 2 Sentences.apkg",
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 3 Sentences.apkg",
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 4 Sentences.apkg",
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 5 Sentences.apkg",
    "~/Sync/Personal/korean/apkg-sentences/HTSK Unit 6 Sentences.apkg",
]
