#!/usr/bin/env bash
# .bashrc
# Evan Chen

if [ -f ~/dotfiles/sh-scripts/git-completion.bash ]; then
  # Git magic / Sourcing
  # shellcheck disable=SC2034
  GIT_PS1_SHOWDIRTYSTATE=1
  # shellcheck disable=SC2034
  GIT_PS1_SHOWSTASHSTATE=1
  # shellcheck disable=SC2034
  GIT_PS1_SHOWUPSTREAM="auto"
  source ~/dotfiles/sh-scripts/git-completion.bash
  source ~/dotfiles/sh-scripts/git-prompt.bash
  export PS1='\[\033[0;32m\]\u@\h \[\033[0;33m\]\w$(__git_ps1 " \[\033[1;31m\]#%s")\n\[\033[0m\]\$ '
else
  export PS1='\[\033[0;31m\]\u@\h \[\033[1;37m\]\w\n\[\033[0m\]\$ '
  if [ -f ~/banner ]; then
    cat ~/banner
  fi
fi
export SUDO_PS1='\[\033[0;31m\]\u@\h \[\033[1;37m\]\w\n\[\033[0m\]\$ '

# Exports
export EDITOR='vim'
export TERM='xterm-256color'
export RCLONE_PASSWORD_COMMAND='pass show rclone'
umask 007 # set umask
if [ -d "$HOME"/.texmf ]; then
  export TEXMFHOME="$HOME"/.texmf
fi

# Aliases
alias gpg-loopback="gpg --clearsign --pinentry-mode loopback"
alias python='python3'
alias trash='gio trash'
alias sudo='sudo ' # allows my aliases to get into sudo in bash

export PYTHONPATH="$PYTHONPATH:$HOME/dotfiles/py-scripts"
export PATH=$HOME/.local/bin:$PATH

# Uses the locate utility to find a certain file
function hunt() {
  python3 ~/dotfiles/py-scripts/hunt.py "${1}"
  cd "$(cat /tmp/hunt."$(whoami)")" || exit 1
  pwd
  ls -l --color=tty
}

#It speaks!
alias aoeu="echo I see you are a Dvorak user."
alias bleh="echo Meh."
alias bye="echo So long, and thanks for all the fish."
alias darn="echo Heh."
alias fml="echo HAHAHAHAHA"
alias hello="echo Hello!"
alias hi="echo Hi!"
alias hm="echo Hm?"
alias kk="echo Glad you approve."
alias lolwut="echo idk"
alias meow="echo Here, kitty! \<3"
alias ok="echo Glad you approve."
alias purr="echo Here, kitty! \<3"

#QQ
alias qq="echo QQ!"
alias qqq="echo QQ!"
alias qqqq="echo QQ!"
alias qqqqq="echo QQ!"
alias qqqqqq="echo QQ!"
alias qqqqqqq="echo QQ!"
alias qqqqqqqq="echo QQ!"
alias qqqqqqqqq="echo QQ!"
alias qqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqqqqqq="echo QQ!"
alias qqqqqqqqqqqqqqqqqqq="echo QQ!"

# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Misc :)
alias less='less -R'             # raw control characters
alias diff='diff --color'        # show differences in color
alias grep='grep --color'        # show differences in color
alias egrep='egrep --color=auto' # show differences in color
alias fgrep='fgrep --color=auto' # show differences in color

# Some shortcuts for different directory listings
if [ -f /bin/pacman ]; then
  alias ls='ls --color=tty --quoting-style=literal' # classify files in color
  alias ll='ls -l --color=tty'                      # long list
  alias l='ls -CF'                                  #
elif [ -f /sbin/apk ]; then
  alias ls='ls --color=always' # classify files in color
  alias ll='ls -l --color=tty' # long list
  alias l='ls -CF'             #
elif [ "$(uname)" = Darwin ]; then
  alias ls='ls -G'  # classify files in color
  alias ll='ls -Gl' # long list
  alias l='ls -CF'  #
fi
