all: py3status.ArchMajestic.conf py3status.ArchScythe.conf py3status.ArchAngel.conf

py3status.ArchMajestic.conf: main.conf order.ArchMajestic.conf
	cat $^ > $@
py3status.ArchScythe.conf: main.conf order.ArchScythe.conf
	cat $^ > $@
py3status.ArchAngel.conf: main.conf order.ArchAngel.conf
	cat $^ > $@
