-- vim: ft=conkyrc noexpandtab

local hostname = io.popen("hostname"):read("*a"):gsub("%s+", "")
local minimum_width, minimum_height, font
if hostname == "ArchDiamond" then
	minimum_width = 3000
	minimum_height = 1280
	font = "Exo 2:size=18"
elseif hostname == "ArchScythe" then
	minimum_width = 1440
	minimum_height = 840
	font = "Exo 2:size=12"
elseif hostname == "ArchMajestic" or hostname == "ArchBootes" or hostname == "ArchUmi" then
	minimum_width = 2048
	minimum_height = 960
	font = "Exo 2:size=18"
else
	minimum_width = 1440
	minimum_height = 840
	font = "Exo 2:size=12"
end

conky.config = dofile(os.getenv("HOME") .. "/dotfiles/conky/common.lua")({
	alignment = "bottom_left",
	border_inner_margin = 25,
	font = font,
	gap_x = 32,
	gap_y = 64,
	minimum_width = minimum_width,
	minimum_height = minimum_height,
	update_interval = 300,
	xinerama_head = 0,
})

conky.text = [[
  ${execpi 300 /usr/bin/python3 ~/dotfiles/conky/prettycal.py}
]]
