-- vim: ft=conkyrc noexpandtab

local hostname = io.popen("hostname"):read("*a"):gsub("%s+", "")
local sections = dofile(os.getenv("HOME") .. "/dotfiles/conky/sections.lua")

conky.config = dofile(os.getenv("HOME") .. "/dotfiles/conky/common.lua")({
	alignment = "top_right",
	border_width = 10,
	font = "Exo 2:size=11:semibold",
	gap_x = 20,
	gap_y = 60,
	minimum_width = 360,
	maximum_width = 360,
	update_interval = 3,
})

conky.text = [[
### HOSTNAME
${color9}${font Exo 2:semibold:size=18}${execi 999999999 whoami}@${nodename}
${color7}${font Exo 2:semibold:size=14}You are filled with determination.
${voffset -10}${color0}${stippled_hr}
${voffset 5}
### CPU
${voffset 5}${font5}${color1}[ CPU ] ${voffset 2}${hr 2}${voffset 0}$color
${voffset -35}${alignr}${color2}${font Exo 2:light:size=16}${freq_g}GHz@${acpitemp}${font Exo 2:semibold:size=13}°C
]]
if hostname == "ArchBootes" then
	conky.text = conky.text
		.. [[
		${voffset 7}${alignr}${color7}${font Exo 2:size=20} ${cpu cpu0}% ${voffset -10} ${cpugraph 32,240}
		${voffset -25}${color9}${font DejaVu Sans:light:size=12}${goto 175}Uptime: ${uptime}
		]]
else
	conky.text = conky.text
		.. [[
		${voffset 7}${alignr}${color7}${font Exo 2:size=20} ${cpu cpu0}% ${voffset 5} ${cpugraph 32,240}
		${voffset -42}${color9}${font DejaVu Sans:light:size=12}${goto 175}Uptime: ${uptime}
		]]
end

conky.text = conky.text
	.. [[
### TOP CPU PROCESSES
${voffset 25}${font Exo 2:semibold:size=12}${color8}PROCESS (${processes}) ${goto 155}${color6}CPU%${color8}${goto 220}MEM${goto 290}PID
${font Exo 2:size=12}${voffset -10}${color0}${stippled_hr}${voffset -2}
]] .. sections.top_cpu .. [[
### GPU
]] .. sections.gpu .. [[
### TOP MEM PROCESSES
]] .. sections.memory .. [[
${font Exo 2:semibold:size=12}${voffset 10}${color DA9BE3}PROCESS (${processes}) ${goto 160}${color1}MEM${color DA9BE3}${goto 220}MEM%${goto 290}PID
${font Exo 2:size=12}${voffset -10}${color0}${stippled_hr}${voffset -2}
]] .. sections.top_mem .. [[
### DISK
${voffset 5}${font5}${color1}[ Disk ] ${voffset 2}${hr 2}$color${font}
]] .. sections.disk(2, "/", "/") .. sections.disk(-2, "~", "/home") .. sections.disk(-2, "G", "/steam") .. [[
### VERSION
${voffset -10}${color0}${stippled_hr}
${voffset -10}${font Exo 2:light:size=10}${conky_version}
]]
