name: Lint

on:
  workflow_call: {}

jobs:
  steps:
  - uses: actions/checkout@v2
    with:
      submodules: recursive
  - name: Set up Python
    uses: actions/setup-python@v2
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pyflakes toml yapf codespell

  - name: Run PyFlakes
    run: |
      pyflakes $(git ls-files '*.py' | grep -v "qutebrowser/" | grep -v "ranger/")
  - name: Run YAPF
    run: |
      yapf -d $(git ls-files '*.py' | grep -v "qutebrowser/" | grep -v "ranger/")
  - name: Run spellcheck
    run: |
      codespell $(git ls-files)
