name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

permissions: {}

jobs:
  prek:
    runs-on: ubuntu-latest
    name: "prek"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1
